baseurl: https://vibrant-curie-ca6c6c.netlify.app/
title: meiermattInfo
theme: hugo-theme-nix
languageCode: en-us
menu:
  header:
    - name: post
      url: post
      weight: 0
    - name: resume
      url: res
      weight: 1
params:
  About: Hi I'm Matt Meier and I am currently working on this website. Right now I have only put up my resume and a game review. 
  Feel free to use the drop down menu in the upper right corner to take a look. Links for my github, linkedin, and email are above.
  Email: meiermatt14@gmail.com
  GithubID: meiermatt
  HeaderHostname: home.io
  HeaderUsername: meiermatt
  LinkedInID: https://www.linkedin.com/in/matthew-meier-737032168/
  Name: Matt Meier
  ProfilePicture: /me.jpg
